### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by lwalukie** [barbeau/earth-gravitational-model#3]
Can you add gradle support? Also do you think output from your library is good enough? 
I also wonder if I should substract or add offset as you indicated: 
`double altitudeMeanSeaLevel = altitudeWgs84 + offset;`
to get altitude above see level?

**Comment by barbeau** [comment]
@lwalukie I'm certainly open to porting this to Gradle instead of Maven. It's a side project that I'm not actively using, though, so it's not a top priority of mine at the moment. Pull requests are welcome!

>Also do you think output from your library is good enough?

See https://github.com/barbeau/earth-gravitational-model/issues/1. It looks like some of the bad output I initially flagged in the testing branch could have been from using the wrong EGM. I haven't had an opportunity to circle back and re-test again though with the correct EGM. You can continue the discussion at #1 if you're interested in testing this out.

>I also wonder if I should substract or add offset as you indicated:
double altitudeMeanSeaLevel = altitudeWgs84 + offset;
to get altitude above see level?

I believe you add it based on my docs in the Readme:
https://github.com/barbeau/earth-gravitational-model/tree/egm96Test#usage

It's been almost four years since I've looked at this, though, so no promises :).
